# Generated by Django 3.2.4 on 2021-07-02 14:42

from django.db import migrations, models
import django.db.models.deletion
from swift_lyrics.models import Lyric, Album, Artist


def load_artist_data(apps, schema_editor):
    artist = Artist(name='Taylor Swift', first_year_active=2004)
    artist.save()
    albums = Album.objects.all()
    for album in albums:
        album.artist = artist
        album.save()
        

class Migration(migrations.Migration):

    dependencies = [
        ('swift_lyrics', '0002_auto_20210413_1744'),
    ]

    operations = [
        migrations.RunPython(load_artist_data)
    ]
